import { Sidebar } from "./components/sidebar"
import "../(front)/globals.css"
import { AdminNavbar } from "./components/admin-navbar"
import { auth } from "@/auth"
import { redirect } from "next/navigation"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {

  let session = await auth();
  if (!session) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body>
        <div className="flex flex-col flex-1">
        <AdminNavbar/>
        <div className="flex flex-1">
          <div className="w-2/12">
            <Sidebar/>
          </div>
          <div className="w-10/12">
              <div className="p-5">
                  {children}
              </div>
          </div>
        </div>
        </div>
        
        </body>
    </html>
  )
}
