import { Inter } from "next/font/google";
import "./globals.css";
import { PublicHeader } from "./components/public-header";
import { SessionProvider } from "next-auth/react";
import DbConnect from "@/utils/dbConnect";
import User from "@/models/User";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopper Project E-commerce Services",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    DbConnect();
    // Add your code to store user data here
    let session = await auth();

    if(session){
      if(session.user){
        // Create user if not exists in the database
        let user = await User.findOne({email: session.user.email})
        if(!user){
          user = await User.create({name:session.user.name, email:session.user.email})
        }
      }
    }

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
        <PublicHeader/>
          {children}
        </SessionProvider>
        </body>
    </html>
  );
}
